### ISSUE TITLE
 Install Tomcat packages task failed with TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by jminne** [sprylab/ansible-role-tomcat-ubuntu#1]
I couldn't get this to work on my Trusty system.
The download tasks work fine, but the tomcat install errors out.
# environment

OS version: VERSION="14.04.2 LTS, Trusty Tahr"
ansible version:  2.0.1.0
python: 2.7.6
# simple playbook

> ---
> # file site.yml
> - hosts: 127.0.0.1
>   connection: local
>   
>   roles:
>   - sprylab.tomcat-ubuntu
# error output

TASK [sprylab.tomcat-ubuntu : Install Tomcat packages] *************************
task path: /etc/ansible/roles/sprylab.tomcat-ubuntu/tasks/main.yml:41
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ansible/executor/task_executor.py", line 92, in run
    item_results = self._run_loop(items)
  File "/usr/lib/pymodules/python2.7/ansible/executor/task_executor.py", line 223, in _run_loop
    items = self._squash_items(items, task_vars)
  File "/usr/lib/pymodules/python2.7/ansible/executor/task_executor.py", line 273, in _squash_items
    if templar._contains_vars(name):
  File "/usr/lib/pymodules/python2.7/ansible/template/__init__.py", line 373, in _contains_vars
    return self.environment.block_start_string in data or self.environment.variable_start_string in data
TypeError: argument of type 'NoneType' is not iterable

fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

**Comment by rzimmer** [comment]
This seems to be a bug in the apt module of ansible version 2.0.1.0, see [#15285](https://github.com/ansible/ansible/issues/15285), [#14664](https://github.com/ansible/ansible/issues/14664) or [#1178](https://github.com/ansible/ansible-modules-core/issues/1178).

If downgrading is no option, you may test the workaround mentioned in [#1178](https://github.com/ansible/ansible-modules-core/issues/1178) and report back if it's working.

**Comment by rzimmer** [comment]
The provided workaround works for me, so I just committed a fix. You may need to re-checkout this role. Thanks for reporting this issue!
